In [12]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)

Resolva os seguintes sistemas lineares (Caso exista soluçao):

$$ x + y + z + 2w = 0 \\
    0x + 0y + 0z -4w = 0 \\$$

$$x + 4y + 7z = 1 \\
    2x + 5y + 8z = 2 \\
    3x + 6y + 10z = 1$$

Exerc. 2 -> Crie um dicionario contendo as informacoes sobre 5 capitais do mundo (de sua escolha). Informaçoes: (nome, pais, populacao).

Exerc.3 -> Calcule a integral utilizando a funcao np.cumsum

$$ \int_0^{1} x^2 \sin(2x) e^{-x} dx $$


Exerc.4 -> Considere a função $r(\theta) = 1+\frac{3}{4}\sin(3 \theta)$ para $0 \leq \theta \leq 2 \pi$

1. Faça um plot da função (Nao precisa fazer essa, pois ainda nao vimos o matplotlib)
2. Calcule a área usando a fórmula $A = \int_{0}^{2\pi} \frac{1}{2} r^2 d\theta$
3. Calcule o perímetro usando a fórmula $L = \int_{0}^{2 \pi} \sqrt{r^2 + \left(\frac{dr}{d\theta}\right)^2} d\theta$


Resposta esperada -> A = 4.02831, L = 11.640021

In [13]:
# Exemplo
A = np.array([
    [1, 2, 3],
    [4, 1, 6],
    [7, 8, 1]
])

determinante = np.linalg.det(A)
print(determinante)

inversa = np.linalg.inv(A)
print(' ')
print(inversa)

# Propriedade: A-1A = I

print(' ')
print(inversa @ A)

# A nao tem inversa se determinante for 0

103.99999999999999
 
[[-0.452  0.212  0.087]
 [ 0.365 -0.192  0.058]
 [ 0.24   0.058 -0.067]]
 
[[ 1. -0. -0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
